# Item-based Collaborative Filtering

Import Packages

In [1]:
%run liblecture.py

## Read Data: movies and ratings

Read Movies

In [2]:
movies = pd.read_csv('movielens/movies_w_imgurl.csv')
movies

movieId   imdbId                                              title  \
0           1   114709                                   Toy Story (1995)   
1           2   113497                                     Jumanji (1995)   
2           3   113228                            Grumpier Old Men (1995)   
3           4   114885                           Waiting to Exhale (1995)   
4           5   113041                 Father of the Bride Part II (1995)   
...       ...      ...                                                ...   
9120   162672  3859980                                Mohenjo Daro (2016)   
9121   163056  4262980                               Shin Godzilla (2016)   
9122   163949  2531318  The Beatles: Eight Days a Week - The Touring Y...   
9123   164977    27660                           The Gay Desperado (1936)   
9124   164979  3447228                              Women of '69, Unboxed   

                                           genres  \
0     Adventure|Animation|Children|Comedy|Fantasy   
1                      Adventure|Children|Fantasy   
2                                  Comedy|Romance   
3                            Comedy|Drama|Romance   
4                                          Comedy   
...                                           ...   
9120                      Adventure|Drama|Romance   
9121              Action|Adventure|Fantasy|Sci-Fi   
9122                                  Documentary   
9123                                       Comedy   
9124                                  Documentary   

                                                 imgurl  
0     https://images-na.ssl-images-amazon.com/images...  
1     https://images-na.ssl-images-amazon.com/images...  
2     https://images-na.ssl-images-amazon.com/images...  
3     https://images-na.ssl-images-amazon.com/images...  
4     https://images-na.ssl-images-amazon.com/images...  
...                                                 ...  
9120  https://images-na.ssl-images-amazon.com/images...  
9121  https://images-na.ssl-images-amazon.com/images...  
9122  https://images-na.ssl-images-amazon.com/images...  
9123  https://images-na.ssl-images-amazon.com/images...  
9124  https://images-na.ssl-images-amazon.com/images...  

[9125 rows x 5 columns]

Read Rating Data

In [3]:
ratings = pd.read_csv('ratings-9_1.csv')

train = ratings[ratings['type'] == 'train'][['userId', 'movieId', 'rating']]
test = ratings[ratings['type'] == 'test'][['userId', 'movieId', 'rating']]

## Convert Ratings to Item-User Sparse Matrix
### Create Index to Id Maps

In [4]:
movieIds = train.movieId.unique()

movieIdToIndex = {}
indexToMovieId = {}

rowIdx = 0

for movieId in movieIds:
    movieIdToIndex[movieId] = rowIdx
    indexToMovieId[rowIdx] = movieId
    rowIdx += 1

In [5]:
userIds = train.userId.unique()

userIdToIndex = {}
indexToUserId = {}

colIdx = 0

for userId in userIds:
    userIdToIndex[userId] = colIdx
    indexToUserId[colIdx] = userId
    colIdx += 1

### Creat Item-User Sparse Matrix

In [6]:
import scipy.sparse as sp

rows = []
cols = []
vals = []

for row in train.itertuples():
    rows.append(movieIdToIndex[row.movieId])
    cols.append(userIdToIndex[row.userId])
    vals.append(row.rating)

coomat = sp.coo_matrix((vals, (rows, cols)), shape=(rowIdx, colIdx))

matrix = coomat.todense()
matrix

matrix([[2.5, 0. , 0. , ..., 0. , 0. , 0. ],
        [3. , 0. , 0. , ..., 0. , 0. , 0. ],
        [2. , 0. , 0. , ..., 0. , 0. , 0. ],
        ...,
        [0. , 0. , 0. , ..., 0. , 0. , 0. ],
        [0. , 0. , 0. , ..., 0. , 0. , 0. ],
        [0. , 0. , 0. , ..., 0. , 0. , 0. ]])

## Compute Item-Item Similarities

Compute $l_2$-norm

In [7]:
from numpy import linalg as LA

norms = LA.norm(matrix, ord = 2, axis=1)
norms

array([20.71, 20.35, 22.94, ...,  3.  ,  1.  ,  1.  ])

Normalize Row Vectors

In [8]:
normmat = np.divide(matrix.T, norms).T
normmat

matrix([[0.12, 0.  , 0.  , ..., 0.  , 0.  , 0.  ],
        [0.15, 0.  , 0.  , ..., 0.  , 0.  , 0.  ],
        [0.09, 0.  , 0.  , ..., 0.  , 0.  , 0.  ],
        ...,
        [0.  , 0.  , 0.  , ..., 0.  , 0.  , 0.  ],
        [0.  , 0.  , 0.  , ..., 0.  , 0.  , 0.  ],
        [0.  , 0.  , 0.  , ..., 0.  , 0.  , 0.  ]])

Compute Similarities ( = inner product)

In [9]:
sims = pd.DataFrame(data = np.matmul(normmat, normmat.T), index = movieIds, columns=movieIds)
sims

31      1061    1129    1172    1287    1293    1339    1343    1371    \
31       1.00    0.20    0.13    0.07    0.09    0.15    0.07    0.18    0.12   
1061     0.20    1.00    0.25    0.18    0.14    0.13    0.25    0.20    0.16   
1129     0.13    0.25    1.00    0.17    0.25    0.16    0.26    0.30    0.34   
1172     0.07    0.18    0.17    1.00    0.27    0.33    0.12    0.12    0.11   
1287     0.09    0.14    0.25    0.27    1.00    0.32    0.17    0.07    0.18   
...       ...     ...     ...     ...     ...     ...     ...     ...     ...   
64997    0.00    0.00    0.00    0.00    0.00    0.00    0.15    0.00    0.00   
72380    0.00    0.00    0.00    0.00    0.00    0.00    0.15    0.00    0.00   
129      0.00    0.15    0.00    0.00    0.00    0.00    0.13    0.00    0.00   
4736     0.00    0.15    0.00    0.00    0.00    0.00    0.13    0.00    0.00   
6425     0.00    0.00    0.00    0.00    0.00    0.00    0.00    0.00    0.00   

       1405    ...  134528  134783  137595  138204  60832   64997   72380   \
31       0.14  ...     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
1061     0.23  ...     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
1129     0.31  ...     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
1172     0.16  ...     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
1287     0.18  ...     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
...       ...  ...     ...     ...     ...     ...     ...     ...     ...   
64997    0.14  ...     0.0     0.0     0.0     0.0     1.0     1.0     1.0   
72380    0.14  ...     0.0     0.0     0.0     0.0     1.0     1.0     1.0   
129      0.00  ...     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
4736     0.00  ...     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
6425     0.00  ...     0.0     0.0     0.0     0.0     0.0     0.0     0.0   

       129     4736    6425    
31       0.00    0.00     0.0  
1061     0.15    0.15     0.0  
1129     0.00    0.00     0.0  
1172     0.00    0.00     0.0  
1287     0.00    0.00     0.0  
...       ...     ...     ...  
64997    0.00    0.00     0.0  
72380    0.00    0.00     0.0  
129      1.00    1.00     0.0  
4736     1.00    1.00     0.0  
6425     0.00    0.00     1.0  

[8740 rows x 8740 columns]

### Similarity Example

In [10]:
movieIdx = 6

rels = sims.iloc[movieIdx,:].sort_values(ascending=False).head(6)[1:]

displayMovies(movies, [indexToMovieId[movieIdx]])
displayMovies(movies, rels.index, rels.values)

## User Rating Prediction

In [11]:
userId = 33

userRatings = train[train['userId'] == userId][['movieId', 'rating']] 

userRatings

movieId  rating
6176       19     3.0
6177       88     3.0
6178      157     1.0
6179      231     3.0
6180      344     4.0
...       ...     ...
6309     5282     4.0
6310     5339     4.0
6311     5483     4.0
6312     5669     4.0
6313     5673     5.0

[129 rows x 2 columns]

### Predict Ratings

In [12]:
recSimSums = sims.loc[userRatings['movieId'].values, :].sum().values

recWeightedRatingSums = np.matmul(sims.loc[userRatings['movieId'].values, :].T.values, userRatings['rating'].values)

recItemRatings = pd.DataFrame(data = np.divide(recWeightedRatingSums, recSimSums), index=sims.index)

recItemRatings.columns = ['pred']

recItemRatings

<ipython-input-12-2516b5a774d1>:5: RuntimeWarning: invalid value encountered in true_divide
  recItemRatings = pd.DataFrame(data = np.divide(recWeightedRatingSums, recSimSums), index=sims.index)


pred
31     3.43
1061   3.38
1129   3.36
1172   3.49
1287   3.42
...     ...
64997  3.23
72380  3.23
129    3.00
4736   3.00
6425   4.00

[8740 rows x 1 columns]

In [13]:
top30Movies = recItemRatings.sort_values(by='pred', ascending=False).head(30)

displayMovies(movies, top30Movies.index, top30Movies['pred'].values)

### Compute Errors (MAE, RMSE)

In [14]:
userTestRatings = pd.DataFrame(data=test[test['userId'] == userId])

temp = userTestRatings.join(recItemRatings.loc[userTestRatings['movieId']], on='movieId')

mae = getMAE(temp['rating'], temp['pred'])
rmse = getRMSE(temp['rating'], temp['pred'])

print(f"MAE : {mae:.4f}")
print(f"RMSE: {rmse:.4f}")

MAE : 0.7424
RMSE: 0.8455


### Compare Logs and Recommendations

In [15]:
logs = userRatings.sort_values(by='rating', ascending=False).head(20)
recs = recItemRatings.sort_values(by='pred', ascending=False).head(20)

In [16]:
displayMovies(movies, logs['movieId'].values, logs['rating'].values)
displayMovies(movies, recs.index, recs['pred'].values)